# Generated by Django 4.2 on 2023-05-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentPrice',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.product')),
                ('price1', models.FloatField(default=0)),
                ('price2', models.FloatField(default=0)),
                ('price3', models.FloatField(default=0)),
                ('price4', models.FloatField(default=0)),
                ('price5', models.FloatField(default=0)),
                ('price6', models.FloatField(default=0)),
            ],
        ),
    ]
