# Generated by Django 4.2 on 2023-05-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recentprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentPrice',
        ),
    ]
