# Generated by Django 4.2 on 2023-05-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_recentprice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentprice',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='usercollect',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercollect',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='usercollect',
            name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='userview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userview',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='userview',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='RecentPrice',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserCollect',
        ),
        migrations.DeleteModel(
            name='UserView',
        ),
    ]
