# Generated by Django 4.2 on 2023-05-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_remove_recentprice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('pics', models.JSONField()),
                ('price', models.FloatField()),
                ('value', models.IntegerField()),
                ('notvalue', models.IntegerField()),
                ('referrer_id', models.IntegerField()),
                ('recommended_time', models.DateTimeField()),
                ('purchase_method', models.CharField(max_length=200)),
                ('recommendation_reason', models.CharField(max_length=200)),
                ('recent_prices', models.JSONField()),
                ('introduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_wechat', models.CharField(max_length=200)),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecentPrice',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.product')),
                ('price1', models.FloatField(default=0)),
                ('price2', models.FloatField(default=0)),
                ('price3', models.FloatField(default=0)),
                ('price4', models.FloatField(default=0)),
                ('price5', models.FloatField(default=0)),
                ('price6', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('user_id', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='UserCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('user_id', 'product_id')},
            },
        ),
    ]
