# Generated by Django 4.2 on 2023-05-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_comment_userview_uservalue_usercollect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='referrer_id',
        ),
    ]
