# Generated by Django 4.2 on 2023-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_referrer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referrer_id',
            field=models.CharField(default='ovN085f-qNQCT3YPKMfw3SXnzJ5w', max_length=200),
            preserve_default=False,
        ),
    ]
