# Generated by Django 4.2 on 2023-05-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uservalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservalue',
            name='id',
        ),
        migrations.AlterField(
            model_name='uservalue',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user'),
        ),
    ]
