# Generated by Django 4.2 on 2023-05-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_uservalue_id_alter_uservalue_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserValue',
        ),
    ]
