# Generated by Django 4.2 on 2023-05-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_uservalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_or_not', models.IntegerField(choices=[(0, 'Not Value'), (1, 'Value')])),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('user_id', 'product_id')},
            },
        ),
    ]
