# Generated by Django 4.2 on 2023-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_uservalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=200)),
                ('avatarUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
